### ISSUE TITLE
接收不到数据怎么解决

### ISSUE THREAD

**Issue by LiuQingying** [xmaihh/Android-Serialport#23]
type=1400 audit(0.0:2416): avc: denied { read } for name="ttyS5" dev="tmpfs" ino=10395 scontext=u:r:untrusted_app:s0:c120,c256,c512,c768 tcontext=u:object_r:serial_device:s0 tclass=chr_file permissive=1 app=com.ex.serialport
2023-04-13 17:19:50.217 m.ex....port                    I  type=1400 audit(0.0:2417): avc: denied { write } for name="ttyS5" dev="tmpfs" ino=10395 scontext=u:r:untrusted_app:s0:c120,c256,c512,c768 tcontext=u:object_r:serial_device:s0 tclass=chr_file permissive=1 app=com.ex.serialport
2023-04-13 17:19:50.220 Thread-6                        I  type=1400 audit(0.0:2420): avc: denied { getattr } for path="/dev/ttyS5" dev="tmpfs" ino=10395 scontext=u:r:untrusted_app:s0:c120,c256,c512,c768 tcontext=u:object_r:serial_device:s0 tclass=chr_file permissive=1 app=com.ex.serialport
请教一下，接收不到数据，是上面的错误引起的吗？安卓端能解决吗

**Comment by xmaihh** [comment]
It's depends of SELinux restrictions. You cannot do so much to avoid it.

In easy words: it means that there is "someone" that has tried to "{read}" something but SELinux stops it because that App wasn't found in the "trusted" list of SELinux. Usually some specific and dangerous locations of the System are restricted from installed Apps, so SELinux stops to read/wrote/execute things in/from that locations.

The given SELinux violation:
```
type=1400 audit(0.0:2416): avc: denied { read } for name="ttyS5" dev="tmpfs" ino=10395 scontext=u:r:untrusted_app:s0:c120,c256,c512,c768 tcontext=u:object_r:serial_device:s0 tclass=chr_file permissive=1 app=com.ex.serialport
```
Below I'll try to give explanation of important parts of above violation:

`denied { read }` : **Operation Permission State** : The denied permission that was requested / executed. In this case, it is a read operation. SELinux denying permission to execute read dir/file operation.

`name="ttyS5"`: **Target name** : The name of the target (in this case, the file/dir name) which your application, probably, trying to read.

`scontext=u:r:untrusted_app:s0` : **Source Context** : The Source Context for this security violation. This indicates which domain/process is trying to execute read functionality. Here, untrusted_app applications are those which are launched by zygote

`tcontext=u:object_r:serial_device:s0` : **Target Context** : The security context of the target resource (in this case the file). Here, the source tried to read file in serial_device file system which has been denied.

`tclass=chr_file` : **Target Class** : The class of the target.

In one sentence, SELinux denied the permission to untrusted_app to read the ttyS5 file in serial_device.

From Google source, check SEPolicy file [untrusted_app.te](https://android.googlesource.com/platform/system/sepolicy/+/android-n-preview-2/untrusted_app.te#160) how the permission has been denied.

To avoid it you should rebuild the ROM after changed specific files about SELinux where you have to add your App in the "trusted zone".

You can install a different Kernel with a different SELinux settings.
